### ISSUE TITLE
Too long

### ISSUE THREAD

**Issue by deepfates** [transcendentprogressivism/manifesto#5]
This is a wall of slop. Manifestos should be tight, persuasive calls to action. You need to be able to gather a big coalition around a simple idea. Every new idea you add cuts down your potential audience.

**Comment by vmfunc** [comment]
What is your suggestion then, cutting it down in different documents?

**Comment by deepfates** [comment]
No, delete most of it. I literally can't tell if there's a valuable idea here because it's a dense wall of noise indistinguishable from any other LLM outputs

**Comment by deepfates** [comment]
I see you don't have any interest in succeeding. Let me know when you realize I was right! Goodbye
